[project]
name = "mongo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "print>=1.3.0",
    "pymongo[srv]>=4.15.4",
]
